name: brew test-bot
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test-bot:
    strategy:
      matrix:
        os: [macos-14, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: brew test-bot --only-formulae --root-url=https://github.com/<user>/homebrew-docrest/releases/download/test-bot
